server:
  port: 8761
spring:
  application:
    name: eureka-service
  security:
    user:
      name: eureka
      password: password
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
