server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: motorcycle-service
          uri: lb://motorcycle-service
          predicates:
            - Path=/motorcycle/**
management:
  tracing:
    sampling:
      probability: 1.0