server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/alejorcode/microservices-1
          search-paths: config-data
  application:
    name: config-service
