server:
  port: 8083
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: keycloak
          uri: https://github.com/alejorcode/microservices-1
          search-paths: config-data

     